version: '3'
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    environment:
      # here it is the name of service "auth"
      - AUTH_ADDRESS=auth
    ports:
      - '8080:8080'
  tasks:
    build: ./tasks-api
    ports:
      - '8000:8000'
    environment:
      - AUTH_ADDRESS=auth
        # this folder should be present in the tasks-api container
      - TASKS_FOLDER=tasks
