apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        # both of these containers will be in the same pod
        - name: tasks
          image: ugulzar4512/task-tasks
          env:
            # in the same pod, we can access other containers through "localhost"
            # "auth-srv" is the name of the service of auth-depl
            - name: AUTH_ADDRESS
              # "auth-srv" is actually the name of ClusterIP service of auth-depl
              # we have to define the ports, both for domain names, and for using ip addresses, or ip address env variables, we have to specify the port

              # <service_name>.<namespace>
              # in case of default remove the namespace
              value: auth-srv
            - name: TASKS_FOLDER
              value: tasks
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-srv
spec:
  selector:
    # select all the pods with the label "app:tasks"
    app: tasks
  # LB creates an automatic ip address, and it also
  # distributes the requests, to all the pods, (even
  # on multiple nodes)
  # Ip address is also independent to the node, but in NodePort, ip address is dependent to the node
  type: LoadBalancer
  ports:
    - protocol: TCP
      # outside facing port on this service ip address
      port: 8000
      # it is the port inside of the pod (or container)
      targetPort: 8000
