apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        # both of these containers will be in the same pod
        - name: users
          image: ugulzar4512/task-users
          env:
            # in the same pod, we can access other containers through "localhost"
            # "auth-srv" is the name of the service of auth-depl
            - name: AUTH_ADDRESS
              # "auth-srv" is actually the name of ClusterIP service of auth-depl
              # we have to define the ports, both for domain names, and for using ip addresses, or ip address env variables, we have to specify the port

              # <service_name>.<namespace>
              # in case of default remove the namespace
              value: auth-srv
---
apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    # select all the pods with the label "app:users"
    app: users
  # LB creates an automatic ip address, and it also
  # distributes the requests, to all the pods, (even
  # on multiple nodes)
  # Ip address is also independent to the node, but in NodePort, ip address is dependent to the node

  # currently this is not used by frontend, to access it itself, we have to use LoadBalancer
  type: ClusterIP # LoadBalancer
  ports:
    - protocol: TCP
      # outside facing port on this service ip address
      port: 8080
      # it is the port inside of the pod (or container)
      targetPort: 8080
